import Footer from '@/components/Footer'
import Header from '@/components/Footer'
import '@/styles/globals.css'
import Head from 'next/head'
import Home from './Home'

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
          <title>harwift-resume/cv-maker</title>
          <meta
              name='description'
              content='Generated by create next-app'
          />
          <meta
              name='viewport'
              content='width=device-width , initial-scale = 1'
          />
          <link rel='icon' href='/favicon.ico'/>
          <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
          <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500&family=Sono&family=Source+Sans+Pro:wght@400;700&display=swap" rel="stylesheet"/>
      </Head>
      <Home/>
    </>
  )
}
